- name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.wintkaythweaugn }}
          password: ${{ secrets.100%Wintisperfect }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # <--- ဒါက Docker Hub ကို ပို့ခိုင်းတာပါ
          # tags မှာ test-build လို့ မရေးဘဲ အောက်ကအတိုင်း ရေးပေးပါ
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-ai-react:latest